### ISSUE TITLE
[feature] - add support for markdown rendering and WYSIWYG Editing

### ISSUE THREAD

**Issue by kempsterrrr** [Developer-DAO/cms#12]
As per [this converstion](https://discord.com/channels/883478451850473483/884852584941232169/1004485488813551636) is discurd, to support the implementation of the terms and privacy pages in the CMS we need to allow CMS users to author content using a WYSIWYG editor and render this on the front end in a simple way.

The suggested goals are:
- allow authors to edit content in a WYSIWYG editor in the CMS
- be able to render this on the UI with one component that globally applies styles to all markdown generated content from CMS

Tailwind css achieves this with an official [typography plugin](https://tailwindcss.com/docs/typography-plugin). A Chakra maintainer has created a simialr library called [Prose](https://github.com/nikolovlazar/chakra-ui-prose).

**Comment by andriishupta** [comment]
@kempsterrrr - Strapi has markdown support out of the box:

if we want to change editor, we could check out what plugins they have

so far we just need to create RichText fields where we want

I added the Markup component, but this RichText is the default field that could be added anywhere

![image](https://user-images.githubusercontent.com/10981565/183094462-8d1afee8-d071-485f-8065-cb689c968752.png)

![image](https://user-images.githubusercontent.com/10981565/183094486-458515d3-ac36-4caa-b02e-23cda4f9e324.png)

![image](https://user-images.githubusercontent.com/10981565/183095240-4cf33667-7b61-4bc8-bd6c-690fdd8a8bab.png)
