### ISSUE TITLE
[Chore]: Add CMS Seed data for Development environment

### ISSUE THREAD

**Issue by kempsterrrr** [Developer-DAO/cms#3]
To ensure a consistent and smooth development experience, we should create some seed data to pre-populate the CMS when built locally in dev.

**Comment by andriishupta** [comment]
@kempsterrrr @mhmulford0 I would like to pick it up if you don't mind

also, I am thinking about the developerdao.com experience:

as I understand so far(I will get familiar more with both projects soon), to develop frontend we would need to have cms repository running locally

we could do:
- force developerdao devs to use cms's dockerfile / build cms without docker with "npm run dev"
- git submodule and build docker file with cms directly
- have a docker registry(do digital ocean has their private "registry" or something)

what do you think?
could be as separate future enhancement

**Comment by kempsterrrr** [comment]
awesome man. Yes please go ahead and take this, might be worth you, @mhmulford0 and I jumping on a call when you have an idea of how to impliment this.

Regarding the DX across these two projects. The plan is to merge them into a monorepo using turbo repo, I've opened an issues for this 👉  #4 - haven't started this as didn't want to distract from getting the website live and moving forward with feature improvements.

Maybe it makes sense to do it all in one go? What do you think @mhmulford0 ? I've been figuring out turborepo on my personal site (seems pretty easy to use) although I've never migrated two seperate repo's to one monorepo before.

**Comment by kempsterrrr** [comment]
@andriishupta if you haven't already, please can you connect your Github account to DeWork :)

**Comment by andriishupta** [comment]
@kempsterrrr 👍 , connected

**Comment by andriishupta** [comment]
@kempsterrrr @mhmulford0 

I have checked out Strapi and found the way to generate seed data:

basically, on [bootstrap.js](https://docs.strapi.io/developer-docs/latest/setup-deployment-guides/configurations/optional/functions.html#register) configuration,

<img width="779" alt="image" src="https://user-images.githubusercontent.com/10981565/181090105-c3b512b0-56fa-4696-bdce-cb4bb49cbd90.png">

I would use [@faker-js/faker](https://www.npmjs.com/package/@faker-js/faker) to fulfill all existing collections programmatically with "real data" and actual connections

there are not many articles about it, but strapi by themselves posted videos of how to do it:
https://strapi.io/video-library/generate-dummy-data-in-strapi
https://strapi.io/video-library/import-data-from-file

I will try "make it smart" by providing some `process.env` variables, so devs will be able to _re-create_ OR _keep data_ on server start(by documentation, this runs on every start-up)

Also, I will make sure this script runs only for development

**Comment by mhmulford0** [comment]
They have made the process pretty easy for us! I think your plan makes sense and should be good to move forward.

My thoughts are to have the seed process run in a post-install script. And also set up a script to drop all tables and re-seed for local dev. That way, in case a dev gets themselves in a bad spot they can get back.

**Comment by andriishupta** [comment]
@mhmulford0, post-install won't work, cause we don't have `/cache` / `/tmp` / `/build` folders at that point - strapi won't have SQLite to save seed data, etc.

Yes, that is what I meant by "make it smart" - I would provide DX for "oh no, I have messed up".
In the documentation, "bootstrap.js runs on every server start" - so I would also _"make it smart"_ to **not SEED data on each start**, but **RE-SEED** when we want it

thinking about `npm run start:clean` / `npm run develop:clean`
also, thinking to have separate script to run it manually `npm run seed`
will see :)

Let me start, and I will come back with a draft where we could provide some additional changes - so far, so good with bootstrap.js and ideas that we need to make it "smooth" 🚀

**Comment by mhmulford0** [comment]
Good info about the temp directories! All that sounds great. Let us know if we can support you any further. Thank you.

**Comment by andriishupta** [comment]
@kempsterrrr @mhmulford0 

Hey 👋 
I have implemented the PR, and it is in the "ready to merge" state.

One thing for PR: do I need to squash commit or not? some projects want to have 1. Others - don't care.

Please, review!

--
One general question - do we need "hero_image" in Project to be localized? isn't it an avatar?

**Comment by kempsterrrr** [comment]
> One thing for PR: do I need to squash commit or not? some projects want to have 1. Others - don't care.

what do you think? cc @mhmulford0 - defer to you chaps as my git isn't fantastic tbh 👀 

> do we need "hero_image" in Project to be localized? isn't it an avatar?

hero image is the main image for the project, this will also show up in previews when the project page is shared on social media, something like this:
![Screenshot 2022-07-27 at 21 43 04](https://user-images.githubusercontent.com/9025997/181368415-a5f23bed-e6e6-4fd6-85f0-ad4674170346.png)

I'm not sure what localizing an image means. @mhmulford0 ?

**Comment by mhmulford0** [comment]
I tend to prefer squashing since i make a lot of "correction" commits. As far as localization, every text field can be localized in Strapi, so it gives you the option. It should not be localized @andriishupta since it is going to be a URL

**Comment by andriishupta** [comment]
@mhmulford0, for example, Contributor's twitter_handle is just a string, and in the Project - the same field is localized, so that's why I asked

I won't touch it now, not to provide additional changes - we can check it out later if needed

**Comment by andriishupta** [comment]
---

review for review again:
- removed `npm` mentions from readme.md
- squashed to 1 commit
