### ISSUE TITLE
[refactor] Merge developerdao.com and cms repo into one monorepo

### ISSUE THREAD

**Issue by kempsterrrr** [Developer-DAO/cms#4]
Currently, the site and cms are living in seperate repos. To improve the DX across both the suggestion is we move to a monorepo powered by Turborepo, example [here](https://github.com/Elvincth/turbo-strapi-nextjs).

Benefits this would bring:

- Share code/types across both codebases
- Reduced context switching when keeping changes across both repo's in-sync
- Simplifies and improve coordination between contributors
- Easy to on-board new contributors 

Not a high prority at the moment but marking this as something to work when we have a spare time.

**Comment by mhmulford0** [comment]
this has been superseded by the new repo https://github.com/Developer-DAO/developer-dao-dot-com
