### ISSUE TITLE
[Feature] - Build data model for Home Page in CMS

### ISSUE THREAD

**Issue by kempsterrrr** [Developer-DAO/cms#6]
Given strapi has now been integrated into the Front End we need to create a data model for populating data on the home page so it can be controlled via the CMS, rather than in code.

Looking at the home page design, at least the following will be required (to be updated during development):

- [ ] Heading
- [ ] Sub-heading
- [ ] Current Status Content Block (might make sense as a component in Strapi TB)
- [ ] Values (might make sense as a component in Strapi
- [ ] Mission
- [ ] Goals
- [x] Partner data for "Our partners section
- [ ] Footer (might make sense as a Strapi component)
- [ ] meta og content
  - [ ] title (max 50–60 characters)
  - [ ] description (max length 155-160 characters)
  - [ ] image (1200:630px)

Unsure if we hard code/not the image of the explorers etc. in the hero above the fold but leaving this here as a reminder.

It may make sense to build a few of these as Components content types in Strapi but don't know enough about this feature to make that call right now. Documentation is [here](https://docs.strapi.io/user-docs/latest/content-types-builder/creating-new-content-type.html#creating-a-new-content-type).

**Comment by andriishupta** [comment]
@kempsterrrr I would like to work on it

from the description - everything is clear so far
I would let you know, if I would have additional questions

**Comment by mhmulford0** [comment]
@andriishupta assigned to you on dework. feel free to have at it!

**Comment by andriishupta** [comment]
cool, thanks!

**Comment by andriishupta** [comment]
@mhmulford0 @kempsterrrr 

I have implemented all required fields: part of them just values and other - Components.

PR is in Draft cause I am in progress with "Fill Home Page" - same as with other collections I want to fill Home Page with data - would finish later today or tomorrow

Meanwhile - please, check GraphQL response that Home Page would have and tell if it looks ok(spoiler - it does ;))

**Comment by andriishupta** [comment]
@mhmulford0 @kempsterrrr 

PR is ready! #8 - a lot of screenshots and how it looks like 💪 

- all above
+ Seeding Home Page
+ Uploading Media! - There are still no docs, but I checked out strapi/strapi GitHub and copied some of the internal calls
To be honest, what I did is not mandatory to describe in Strapi docs, cause it mainly internal functions and plugins
